# -*- coding: utf-8 -*-
"""123120079_Bintang Putra Permana_Modul 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etEokIWh_5sfEWE0Vz5ljIOhBswH2l3q
"""

# Topik 1. Sintaks, Indentasi, dan Komentar
# Judul Program
# Program ini dibuat untuk menampilkan biodata singkat.
# Dibuat oleh: [Nama Anda]
# Tanggal: [Tanggal]

"""
Blok komentar multi-baris.
Ini adalah contoh program Python pertama untuk praktikum.
Program ini hanya akan menampilkan teks ke konsol/terminal.
"""

# Menampilkan judul biodata
print("--- BIODATA SAYA ---")
print("") # Memberikan baris kosong sebagai spasi

# Menampilkan data diri
print("Nama      : Bintang Putra Permana")
print("NIM       : 123120079")
print("Jurusan   : Teknik Geofisika")
print("Angkatan  : 2023")

# Menampilkan hobi
print("Hobi      : Berenang")

print("\n--- Terima Kasih ---") # \n digunakan untuk membuat baris baru

# Perbaiki kode rusak
if 5 > 2:
    print("Lima lebih besar dari dua!")  # Diindentasi 1 tab

# Topik 2. Variabel dan Tipe Data
## 2.1 Kalkulator Luas Lingkaran

print("--- Kalkulator Luas Lingkaran ---") # Judul Program
jari_jari = float(input("Masukkan jari-jari lingkaran (cm): ")) # Meminta input jari-jari
pi = 3.14 # Nilai Pi

# rumus luas lingkaran
luas = pi * (jari_jari ** 2)

# Menampilkan hasil
print(f"\n--- Hasil Perhitungan ---")
print(f"Jari-jari: {jari_jari} cm")
print(f"Luas lingkaran: {luas} cm^2")

## 2.2 Variabel Data Diri
# Mendefinisikan variabel data diri
nama = "Budi Santoso"
umur = 20
tinggi_badan = 1.75  # dalam meter
status_mahasiswa = True

# Mencetak dalam satu kalimat informatif
print(f"Nama saya {nama}, umur {umur} tahun, tinggi badan {tinggi_badan} meter, dan status mahasiswa: {status_mahasiswa}.")

# Topik 3: Operator Python
# 1. Konverter Suhu

# Program Konverter Suhu: Celcius ke Fahrenheit
print("--- Konverter Suhu Celcius ke Fahrenheit ---")

# Meminta input suhu dalam Celcius
celcius = float(input("Masukkan suhu dalam Celcius: "))

# Konversi ke Fahrenheit
fahrenheit = (celcius * 9/5) + 32

# Menampilkan hasil
print(f"{celcius} derajat Celcius = {fahrenheit} derajat Fahrenheit")

# 2. Cek Angka Ganjil/Genap

# Program Cek Angka Ganjil atau Genap
print("--- Cek Angka Ganjil/Genap ---")

# Meminta input bilangan bulat
angka = int(input("Masukkan sebuah bilangan bulat: "))

# Memeriksa ganjil atau genap dengan operator modulus
if angka % 2 == 0:
    print(f"{angka} adalah bilangan genap.")
else:
    print(f"{angka} adalah bilangan ganjil.")

# Topik 4: Struktur Data
# 1. Daftar Belanja

# Program Daftar Belanja
daftar_belanja = []

# Meminta input 3 barang dari pengguna
for i in range(3):
    barang = input(f"Masukkan barang ke-{i+1}: ")
    daftar_belanja.append(barang)

# Mencetak daftar belanja final
print(f"Daftar belanja final: {daftar_belanja}")

# 2. Kontak Telepon

# Dictionary Kontak Telepon
kontak = {
    "nama": "Budi Santoso",
    "no_hp": "081234567890",
    "email": "budi.santoso@example.com"
}

# Mencetak nomor HP teman
print(f"Nomor HP teman: {kontak['no_hp']}")

# Topik 5: Kontrol Alur Program
# 1. Tebak Angka

# Permainan Tebak Angka
angka_rahasia = 17
tebakan = None

print("--- Permainan Tebak Angka ---")
print("Tebak angka antara 1 sampai 100.")

while tebakan != angka_rahasia:
    tebakan = int(input("Masukkan tebakan Anda: "))

    if tebakan < angka_rahasia:
        print("Tebakan Anda terlalu kecil.")
    elif tebakan > angka_rahasia:
        print("Tebakan Anda terlalu besar.")
    else:
        print(f"Selamat! Anda berhasil menebak angka {angka_rahasia}.")

  # 2. Cetak Bilangan Genap

  # Mencetak bilangan genap dari 1 hingga 20
print("Bilangan genap dari 1 hingga 20:")
for angka in range(1, 21):
    if angka % 2 == 0:
        print(angka, end=" ")

# Topik 6: Fungsi dan Modularisasi Program
# 1. Fungsi Greeting

# Fungsi Greeting
def buat_salam(nama):
    return f"Selamat pagi, {nama}."

# Memanggil fungsi dengan nama Anda
salam = buat_salam("Budi")
print(salam)

# 2. Perluas Library Kalkulator
# Ini adalah modul library kalkulator kita.
# Berisi fungsi-fungsi matematika.

def tambah(angka1, angka2):
    """Fungsi ini menjumlahkan dua angka dan mengembalikan hasilnya."""
    return angka1 + angka2

def kurang(angka1, angka2):
    """Fungsi ini mengurangkan dua angka dan mengembalikan hasilnya."""
    return angka1 - angka2

def kali(angka1, angka2):
    """Fungsi ini mengalikan dua angka dan mengembalikan hasilnya."""
    return angka1 * angka2

def bagi(angka1, angka2):
    """
    Fungsi ini membagi dua angka.
    Menambahkan penanganan jika pembagi adalah nol.
    """
    if angka2 == 0:
        return "Error: Tidak bisa dibagi dengan nol!"
    return angka1 / angka2

def pangkat(angka, pangkat):
    """Fungsi ini menghitung angka dipangkatkan dengan pangkat tertentu."""
    return angka ** pangkat

# Ini adalah file utama program kita.
# Kita akan mengimport library yang sudah kita buat.
import kalkulator_lib

def tampilkan_menu():
    """Fungsi untuk menampilkan menu pilihan kepada pengguna."""
    print("\n--- Kalkulator Sederhana ---")
    print("1. Penjumlahan")
    print("2. Pengurangan")
    print("3. Perkalian")
    print("4. Pembagian")
    print("5. Pangkat")
    print("6. Keluar")

# Program utama berjalan dalam loop while
while True:
    tampilkan_menu()
    pilihan = input("Pilih operasi (1/2/3/4/5/6): ")

    if pilihan == '6':
        print("Terima kasih telah menggunakan kalkulator!")
        break

    if pilihan in ['1', '2', '3', '4', '5']:
        try:
            a = float(input("Masukkan angka pertama: "))
            b = float(input("Masukkan angka kedua: "))
        except ValueError:
            print("Input tidak valid. Harap masukkan angka.")
            continue

        hasil = None
        if pilihan == '1':
            hasil = kalkulator_lib.tambah(a, b)
        elif pilihan == '2':
            hasil = kalkulator_lib.kurang(a, b)
        elif pilihan == '3':
            hasil = kalkulator_lib.kali(a, b)
        elif pilihan == '4':
            hasil = kalkulator_lib.bagi(a, b)
        elif pilihan == '5':
            hasil = kalkulator_lib.pangkat(a, b)

        print(f"Hasilnya adalah: {hasil}")
    else:
        print("Pilihan tidak valid. Silakan coba lagi.")