# -*- coding: utf-8 -*-
"""123120079_Bintang Putra Permana_Modul 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhIGgwx5uwa8TXQZNH_cE7VudiyU0hQO
"""

survey = {
    "Survey_A": [
        {"trace_id": 1, "receiver": "R1", "offset": 100, "QC_flag": "OK"},
        {"trace_id": 2, "receiver": "R2", "offset": 150, "QC_flag": "OK"},
        {"trace_id": 3, "receiver": "R3", "offset": 200, "QC_flag": "BAD"}
    ],
    "Survey_B": [
        {"trace_id": 4, "receiver": "R1", "offset": 120, "QC_flag": "OK"},
        {"trace_id": 5, "receiver": "R4", "offset": 250, "QC_flag": "OK"},
        {"trace_id": 6, "receiver": "R2", "offset": 300, "QC_flag": "BAD"}
    ]
}

print("4.1 Sistem Data Survey Seismik")
# Tampilkan semua trace_id yang memiliki QC_flag = BAD.
bad_qc_traces = []

for survey_name, traces in survey.items():
    for trace in traces:
        if trace['QC_flag'] == 'BAD':
            bad_qc_traces.append(trace['trace_id'])

print("1. Trace ID dengan QC_flag 'BAD':", bad_qc_traces)

# Hitung jumlah total trace dari seluruh survey.
total_traces = 0

for survey_name, traces in survey.items():
    total_traces += len(traces)

print(f"2. Jumlah total trace dari seluruh survey: {total_traces}")

# Cari survey yang memiliki jumlah trace paling banyak.
max_traces = 0
survey_dengan_trace_terbanyak = ""

for survey_name, traces in survey.items():
    current_trace_count = len(traces)
    if current_trace_count > max_traces:
        max_traces = current_trace_count
        survey_dengan_trace_terbanyak = survey_name

print(f"3. Survey dengan jumlah trace terbanyak adalah '{survey_dengan_trace_terbanyak}' dengan {max_traces} trace.")

# Buat set berisi semua receiver unik dari seluruh survey.
unique_receivers = set()

for survey_name, traces in survey.items():
    for trace in traces:
        unique_receivers.add(trace['receiver'])

print(f"4. Set Reciever: {unique_receivers}")

# Buat dictionary baru berisi {"receiver": jumlah_trace} untuk menghitung frekuensi kemunculan receiver.
receiver_frequency = {}

for survey_name, traces in survey.items():
    for trace in traces:
        receiver = trace['receiver']
        receiver_frequency[receiver] = receiver_frequency.get(receiver, 0) + 1

print("5. Frekuensi receiver:", receiver_frequency)

# 4.2 Database Sensor
sensor_data = {
    "Sensor_A": [(1, 0.12), (2, 0.15), (3, 0.30)],
    "Sensor_B": [(1, 0.20), (2, 0.18), (3, 0.25)],
    "Sensor_C": [(1, 0.11), (2, 0.10), (3, 0.40)]
}
print("------------------")
print("4.2 Database Sensor")

def cari_amplitudo_maks_dan_waktu(sensor_data):
    hasil_laporan = {}

    for nama_sensor, data_sensor in sensor_data.items():
        maks_amplitudo = float('-inf')
        waktu_maks = None

        for waktu, amplitudo in data_sensor:
            if amplitudo > maks_amplitudo:
                maks_amplitudo = amplitudo
                waktu_maks = waktu

        hasil_laporan[nama_sensor] = {
            "amplitudo_maks": maks_amplitudo,
            "waktu_terjadi": waktu_maks
        }

    return hasil_laporan

laporan_akhir = cari_amplitudo_maks_dan_waktu(sensor_data)
for sensor, data in laporan_akhir.items():
    print(f"Sensor: {sensor}")
    print(f"  Amplitudo Maksimum: {data['amplitudo_maks']}")
    print(f"  Waktu Terjadi (Indeks): {data['waktu_terjadi']}")

print("------------------")

# 4.3 Data Survey Geofisika
data_survei = {
    "Survey_Alpha": {
        "seismik": [
            {"trace_id": 1, "offset": 120, "QC_flag": "OK"},
            {"trace_id": 2, "offset": 300, "QC_flag": "BAD"}
        ],
        "gravitasi": [
            {"point_id": "G1", "nilai": 9.81},
            {"point_id": "G2", "nilai": 9.75}
        ],
        "magnetik": [
            {"point_id": "M1", "nilai": 48.5},
            {"point_id": "M2", "nilai": 49.0}
        ]
    },
    "Survey_Beta": {
        "seismik": [
            {"trace_id": 3, "offset": 200, "QC_flag": "OK"},
            {"trace_id": 4, "offset": 250, "QC_flag": "OK"}
        ],
        "gravitasi": [
            {"point_id": "G3", "nilai": 9.70},
            {"point_id": "G4", "nilai": 9.65}
        ],
        "magnetik": [
            {"point_id": "M3", "nilai": 50.2},
            {"point_id": "M4", "nilai": 49.8}
        ]
    }
}

# 1. QC Data Seismik
def qc_seismik(data, ambang_offset):
    laporan = {}

    for nama_survei, konten in data.items():
        ok = 0
        bad = 0

        for trace in konten["seismik"]:
            if trace["offset"] > ambang_offset:
                trace["QC_flag"] = "BAD"
                bad += 1
            else:
                trace["QC_flag"] = "OK"
                ok += 1

        laporan[nama_survei] = {
            "total_OK": ok,
            "total_BAD": bad
        }

    return laporan

# 2. Statistik Gravitasi
def statistik_gravitasi(data):
    rata_rata = {}
    semua_nilai = []

    for nama_survei, konten in data.items():
        nilai_grav = [g["nilai"] for g in konten["gravitasi"]]
        rata_rata[nama_survei] = sum(nilai_grav) / len(nilai_grav)
        semua_nilai.extend(nilai_grav)

    hasil = {
        "rata_rata_per_survei": rata_rata,
        "nilai_terendah": min(semua_nilai),
        "nilai_tertinggi": max(semua_nilai)
    }

    return hasil

# 3. Analisis Magnetik
def analisis_magnetik(data):
    semua_nilai = []

    for konten in data.values():
        semua_nilai.extend([m["nilai"] for m in konten["magnetik"]])

    nilai_unik_urut = sorted(set(semua_nilai))
    return nilai_unik_urut

ambang_offset = 220

laporan_qc = qc_seismik(data_survei, ambang_offset)
stat_grav = statistik_gravitasi(data_survei)
analisis_mag = analisis_magnetik(data_survei)

print("4.3 Data Survey Geofisika")
print("1. Laporan QC Seismik:")
print(laporan_qc)

print("\n2. Statistik Gravitasi:")
print(stat_grav)

print("\n3. Analisis Magnetik (nilai unik terurut):")
print(analisis_mag)