# -*- coding: utf-8 -*-
"""123120079_Bintang Putra Permana_Modul 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XCF6KBVMRXpOmeyxD3pKfBNe07uW0ry
"""

# 1. IMPORT LIBRARY
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import os

print("Semua library berhasil diimport!")

# 2. KONFIGURASI
class Config:
    """Kelas untuk menyimpan konfigurasi analisis"""
    # File input/output
    INPUT_FILE = "data_mikroseismik.csv"
    OUTPUT_PROCESSED = "data_mikroseismik_terproses.csv"
    OUTPUT_REPORT = "laporan_analisis.txt"
    OUTPUT_VISUALIZATION = "visualisasi_analisis_seismik.png"

    # Parameter analisis
    MIN_MAGNITUDO = 0.0  # Batas minimum magnitudo valid
    DEPTH_THRESHOLD = -1600.0  # Batas kedalaman dangkal-dalam (meter)
    RADIUS_THRESHOLD = 500.0  # Radius zona dekat (meter)
    MONITORING_CENTER = (0.0, 0.0)  # Koordinat pusat monitoring

    # Visualisasi
    PLOT_FIGSIZE = (15, 10)
    PLOT_DPI = 150

config = Config()

# 3. FUNGSI UTILITAS
def create_sample_data(filename: str, n_samples: int = 100) -> pd.DataFrame:
    """
    Membuat data contoh jika file tidak ditemukan.

    Parameters:
    -----------
    filename : str
        Nama file output
    n_samples : int
        Jumlah sampel data

    Returns:
    --------
    pd.DataFrame
        DataFrame berisi data contoh
    """
    print(f"Membuat data contoh dengan {n_samples} sampel...")

    np.random.seed(42)  # Untuk hasil yang konsisten

    # Generate data dasar
    time_range = pd.date_range('2024-01-01', periods=n_samples, freq='H')

    data = {
        'Waktu_UTC': time_range.strftime('%Y-%m-%d %H:%M:%S'),
        'X_m': np.random.uniform(-1000, 1000, n_samples),
        'Y_m': np.random.uniform(-1000, 1000, n_samples),
        'Z_m': np.random.uniform(-3000, -500, n_samples),
        'Magnitudo': np.random.uniform(0.5, 4.5, n_samples)
    }

    # Tambahkan data tidak valid untuk simulasi
    df_sample = pd.DataFrame(data)

    # Data tidak valid: magnitudo negatif, nol, dan NaN
    df_sample.loc[5, 'Magnitudo'] = -1.5
    df_sample.loc[10, 'Magnitudo'] = 0.0
    df_sample.loc[15, 'Z_m'] = np.nan

    # Simpan ke file
    df_sample.to_csv(filename, index=False)
    print(f"Data contoh disimpan sebagai '{filename}'")

    return df_sample

def print_section_header(title: str, width: int = 60):
    """Mencetak header section dengan format rapi"""
    print("\n" + "=" * width)
    print(title.center(width))
    print("=" * width)

def format_float(value: float, decimals: int = 2) -> str:
    """Memformat angka float dengan jumlah desimal tertentu"""
    return f"{value:.{decimals}f}"

# 4. FUNGSI PEMROSESAN DATA
def load_and_inspect_data(filename: str) -> pd.DataFrame:
    """
    Memuat data dari file CSV dan melakukan inspeksi awal.

    Returns:
    --------
    pd.DataFrame
        DataFrame berisi data mentah
    """
    print_section_header("MEMUAT DAN INSPEKSI DATA")

    # Cek apakah file exists
    if not os.path.exists(filename):
        print(f"File '{filename}' tidak ditemukan!")
        print("Membuat data contoh untuk demonstrasi...")
        df = create_sample_data(filename)
    else:
        print(f"Memuat data dari '{filename}'...")
        df = pd.read_csv(filename)

    # Tampilkan informasi data
    print(f"\n📊 Informasi Data:")
    print(f"   • Jumlah data: {df.shape[0]:,} baris × {df.shape[1]} kolom")
    print(f"   • Kolom: {', '.join(df.columns.tolist())}")

    print(f"\n📈 Statistik Deskriptif:")
    numeric_stats = df.describe()
    for col in numeric_stats.columns:
        print(f"   • {col}:")
        print(f"     Min={format_float(numeric_stats[col]['min'])}, "
              f"Max={format_float(numeric_stats[col]['max'])}, "
              f"Mean={format_float(numeric_stats[col]['mean'])}")

    # Cek missing values
    missing = df.isnull().sum()
    if missing.any():
        print(f"\n⚠️  Data Hilang (Missing Values):")
        for col, count in missing[missing > 0].items():
            print(f"   • {col}: {count} nilai ({count/len(df)*100:.1f}%)")

    return df

def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Membersihkan data dengan menghapus nilai tidak valid.

    Returns:
    --------
    pd.DataFrame
        DataFrame yang telah dibersihkan
    """
    print_section_header("PEMBERSIHAN DATA")

    initial_count = len(df)
    print(f"Jumlah data awal: {initial_count:,}")

    # Salin data untuk menghindari warning
    df_clean = df.copy()

    # 1. Hapus data dengan magnitudo tidak valid
    invalid_mag = df_clean['Magnitudo'] <= config.MIN_MAGNITUDO
    df_clean = df_clean[~invalid_mag]
    removed_mag = invalid_mag.sum()

    # 2. Hapus baris dengan nilai NaN
    initial_nan_count = df_clean.isnull().sum().sum()
    df_clean = df_clean.dropna()
    final_nan_count = df_clean.isnull().sum().sum()

    # 3. Hitung statistik pembersihan
    final_count = len(df_clean)
    removed_total = initial_count - final_count

    print(f"✅ Data yang dihapus:")
    print(f"   • Magnitudo tidak valid: {removed_mag:,}")
    print(f"   • Nilai NaN: {initial_nan_count:,}")
    print(f"   • Total dihapus: {removed_total:,}")
    print(f"\n📊 Hasil Pembersihan:")
    print(f"   • Data awal: {initial_count:,}")
    print(f"   • Data bersih: {final_count:,}")
    print(f"   • Persentase valid: {final_count/initial_count*100:.1f}%")

    return df_clean

def preprocess_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Melakukan preprocessing data: konversi tipe dan feature engineering.

    Returns:
    --------
    pd.DataFrame
        DataFrame yang telah diproses
    """
    print_section_header("PREPROCESSING DATA")

    df_processed = df.copy()

    # 1. Konversi tipe data waktu
    print("🕒 Mengonversi kolom waktu...")
    df_processed['Waktu_UTC'] = pd.to_datetime(df_processed['Waktu_UTC'])

    # 2. Hitung jarak horizontal dari pusat monitoring
    print("📏 Menghitung jarak dari pusat monitoring...")
    x0, y0 = config.MONITORING_CENTER
    df_processed['Jarak_Horizontal_m'] = np.sqrt(
        (df_processed['X_m'] - x0) ** 2 +
        (df_processed['Y_m'] - y0) ** 2
    )

    # 3. Klasifikasi kedalaman
    print("🌊 Mengklasifikasikan kedalaman...")
    df_processed['Kategori_Kedalaman'] = pd.cut(
        df_processed['Z_m'],
        bins=[-np.inf, config.DEPTH_THRESHOLD, 0],
        labels=['Dalam', 'Dangkal']
    )

    # 4. Klasifikasi zona
    print("📍 Mengklasifikasikan zona...")
    df_processed['Zona'] = pd.cut(
        df_processed['Jarak_Horizontal_m'],
        bins=[0, config.RADIUS_THRESHOLD, np.inf],
        labels=['Zona Dekat', 'Zona Jauh']
    )

    print("✅ Preprocessing selesai!")
    print(f"\nKolom baru yang ditambahkan:")
    new_cols = [col for col in df_processed.columns if col not in df.columns]
    for col in new_cols:
        print(f"   • {col}")

    return df_processed

def analyze_data(df: pd.DataFrame) -> dict:
    """
    Melakukan analisis statistik pada data.

    Returns:
    --------
    dict
        Dictionary berisi hasil analisis
    """
    print_section_header("ANALISIS DATA")

    results = {
        'total_data': len(df),
        'time_range': {
            'start': df['Waktu_UTC'].min(),
            'end': df['Waktu_UTC'].max()
        }
    }

    # 1. Analisis magnitudo
    magnitudo_stats = df['Magnitudo'].describe()
    results['magnitudo'] = {
        'mean': magnitudo_stats['mean'],
        'std': magnitudo_stats['std'],
        'min': magnitudo_stats['min'],
        'max': magnitudo_stats['max'],
        'q25': magnitudo_stats['25%'],
        'q75': magnitudo_stats['75%']
    }

    # Gempa terbesar dan terkecil
    idx_max = df['Magnitudo'].idxmax()
    idx_min = df['Magnitudo'].idxmin()

    results['gempa_terbesar'] = {
        'magnitudo': df.loc[idx_max, 'Magnitudo'],
        'waktu': df.loc[idx_max, 'Waktu_UTC'],
        'koordinat': (
            df.loc[idx_max, 'X_m'],
            df.loc[idx_max, 'Y_m'],
            df.loc[idx_max, 'Z_m']
        ),
        'jarak': df.loc[idx_max, 'Jarak_Horizontal_m']
    }

    results['gempa_terkecil'] = {
        'magnitudo': df.loc[idx_min, 'Magnitudo'],
        'waktu': df.loc[idx_min, 'Waktu_UTC'],
        'koordinat': (
            df.loc[idx_min, 'X_m'],
            df.loc[idx_min, 'Y_m'],
            df.loc[idx_min, 'Z_m']
        ),
        'jarak': df.loc[idx_min, 'Jarak_Horizontal_m']
    }

    # 2. Analisis kedalaman
    results['kedalaman'] = {
        'mean': df['Z_m'].mean(),
        'min': df['Z_m'].min(),
        'max': df['Z_m'].max()
    }

    # Distribusi kategori kedalaman
    depth_dist = df['Kategori_Kedalaman'].value_counts()
    results['distribusi_kedalaman'] = {
        'dangkal': depth_dist.get('Dangkal', 0),
        'dalam': depth_dist.get('Dalam', 0),
        'persen_dangkal': depth_dist.get('Dangkal', 0) / len(df) * 100
    }

    # 3. Analisis jarak
    results['jarak'] = {
        'mean': df['Jarak_Horizontal_m'].mean(),
        'min': df['Jarak_Horizontal_m'].min(),
        'max': df['Jarak_Horizontal_m'].max()
    }

    # Distribusi zona
    zone_dist = df['Zona'].value_counts()
    results['distribusi_zona'] = {
        'dekat': zone_dist.get('Zona Dekat', 0),
        'jauh': zone_dist.get('Zona Jauh', 0),
        'persen_dekat': zone_dist.get('Zona Dekat', 0) / len(df) * 100
    }

    # Statistik zona dekat
    zona_dekat = df[df['Zona'] == 'Zona Dekat']
    if len(zona_dekat) > 0:
        results['zona_dekat_stats'] = {
            'count': len(zona_dekat),
            'mean_magnitudo': zona_dekat['Magnitudo'].mean(),
            'mean_kedalaman': zona_dekat['Z_m'].mean()
        }

    print("✅ Analisis selesai!")
    return results

def visualize_data(df: pd.DataFrame, results: dict):
    """
    Membuat visualisasi data seismik.
    """
    print_section_header("VISUALISASI DATA")

    fig, axes = plt.subplots(2, 3, figsize=config.PLOT_FIGSIZE)
    fig.suptitle('Analisis Data Mikroseismik', fontsize=16, fontweight='bold')

    # 1. Histogram Magnitudo
    ax = axes[0, 0]
    ax.hist(df['Magnitudo'], bins=20, edgecolor='black', alpha=0.7, color='skyblue')
    ax.set_xlabel('Magnitudo')
    ax.set_ylabel('Frekuensi')
    ax.set_title('Distribusi Magnitudo')
    ax.grid(True, alpha=0.3)
    ax.axvline(results['magnitudo']['mean'], color='red',
               linestyle='--', label=f"Mean: {results['magnitudo']['mean']:.2f}")
    ax.legend()

    # 2. Histogram Kedalaman
    ax = axes[0, 1]
    colors = ['lightcoral' if x > config.DEPTH_THRESHOLD else 'steelblue'
              for x in df['Z_m']]
    ax.hist(df['Z_m'], bins=20, edgecolor='black', alpha=0.7, color='steelblue')
    ax.axvline(config.DEPTH_THRESHOLD, color='red', linestyle='--',
               label=f'Batas ({config.DEPTH_THRESHOLD} m)')
    ax.set_xlabel('Kedalaman (m)')
    ax.set_ylabel('Frekuensi')
    ax.set_title('Distribusi Kedalaman')
    ax.legend()
    ax.grid(True, alpha=0.3)

    # 3. Scatter Plot X-Y dengan Magnitudo
    ax = axes[0, 2]
    scatter = ax.scatter(df['X_m'], df['Y_m'],
                        c=df['Magnitudo'], cmap='viridis',
                        s=50, alpha=0.6, edgecolors='k', linewidth=0.5)

    # Tambahkan lingkaran radius
    circle = plt.Circle(config.MONITORING_CENTER, config.RADIUS_THRESHOLD,
                       color='red', fill=False, linestyle='--', linewidth=2,
                       label=f'Radius {config.RADIUS_THRESHOLD} m')
    ax.add_patch(circle)

    ax.set_xlabel('X (m)')
    ax.set_ylabel('Y (m)')
    ax.set_title('Peta Sebaran Gempa')
    ax.grid(True, alpha=0.3)
    ax.axhline(y=0, color='k', linestyle='-', alpha=0.3)
    ax.axvline(x=0, color='k', linestyle='-', alpha=0.3)
    ax.legend()
    plt.colorbar(scatter, ax=ax, label='Magnitudo')

    # 4. Magnitudo vs Kedalaman
    ax = axes[1, 0]
    scatter = ax.scatter(df['Magnitudo'], df['Z_m'],
                        c=df['Jarak_Horizontal_m'], cmap='plasma',
                        s=40, alpha=0.7, edgecolors='k', linewidth=0.5)
    ax.set_xlabel('Magnitudo')
    ax.set_ylabel('Kedalaman (m)')
    ax.set_title('Magnitudo vs Kedalaman')
    ax.grid(True, alpha=0.3)
    plt.colorbar(scatter, ax=ax, label='Jarak (m)')

    # 5. Magnitudo vs Waktu
    ax = axes[1, 1]
    ax.scatter(df['Waktu_UTC'], df['Magnitudo'], s=20, alpha=0.6)
    ax.set_xlabel('Waktu')
    ax.set_ylabel('Magnitudo')
    ax.set_title('Magnitudo vs Waktu')
    ax.grid(True, alpha=0.3)
    plt.xticks(rotation=45)

    # 6. Pie Chart Distribusi
    ax = axes[1, 2]
    labels = ['Dangkal', 'Dalam']
    sizes = [
        results['distribusi_kedalaman']['dangkal'],
        results['distribusi_kedalaman']['dalam']
    ]
    colors_pie = ['lightcoral', 'steelblue']
    ax.pie(sizes, labels=labels, colors=colors_pie, autopct='%1.1f%%',
           startangle=90, shadow=True)
    ax.set_title('Distribusi Kedalaman Gempa')

    plt.tight_layout()
    plt.savefig(config.OUTPUT_VISUALIZATION, dpi=config.PLOT_DPI,
                bbox_inches='tight')
    plt.show()

    print(f"✅ Visualisasi disimpan sebagai '{config.OUTPUT_VISUALIZATION}'")

def generate_report(results: dict, df: pd.DataFrame):
    """
    Membuat laporan analisis dalam format teks.
    """
    print_section_header("MEMBUAT LAPORAN")

    report_lines = []

    # Header
    report_lines.append("=" * 70)
    report_lines.append("LAPORAN ANALISIS DATA MIKROSEISMIK".center(70))
    report_lines.append("=" * 70)
    report_lines.append(f"\nTanggal Analisis: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append(f"Total Data Valid: {results['total_data']:,} kejadian")
    report_lines.append(f"Rentang Waktu: {results['time_range']['start']} hingga {results['time_range']['end']}")

    # 1. Ringkasan Eksekutif
    report_lines.append("\n" + "-" * 70)
    report_lines.append("RINGKASAN EKSEKUTIF")
    report_lines.append("-" * 70)

    # Buat ringkasan berdasarkan analisis
    if results['distribusi_zona']['persen_dekat'] > 20:
        report_lines.append("⚠️  AKTIVITAS SIGNIFIKAN DI ZONA DEKAT!")
        report_lines.append(f"   • {results['distribusi_zona']['dekat']} kejadian dalam radius {config.RADIUS_THRESHOLD} m")
        report_lines.append("   • Rekomendasi: Tingkatkan monitoring dan evaluasi operasional")
    else:
        report_lines.append("✅ AKTIVITAS DALAM BATAS NORMAL")
        report_lines.append("   • Sebagian besar kejadian berada di zona jauh")

    if results['distribusi_kedalaman']['persen_dangkal'] > 60:
        report_lines.append(f"\n📈 DOMINANSI GEMPA DANGKAL")
        report_lines.append(f"   • {results['distribusi_kedalaman']['persen_dangkal']:.1f}% kejadian pada kedalaman > {abs(config.DEPTH_THRESHOLD):.0f} m")
        report_lines.append("   • Kemungkinan terkait aktivitas dekat permukaan")

    # 2. Analisis Detail
    report_lines.append("\n" + "-" * 70)
    report_lines.append("ANALISIS DETAIL")
    report_lines.append("-" * 70)

    # Magnitudo
    report_lines.append("\n📊 ANALISIS MAGNITUDO:")
    mag = results['magnitudo']
    report_lines.append(f"   • Rata-rata: {format_float(mag['mean'])}")
    report_lines.append(f"   • Range: {format_float(mag['min'])} - {format_float(mag['max'])}")
    report_lines.append(f"   • Standar Deviasi: {format_float(mag['std'])}")

    # Gempa terbesar
    g_max = results['gempa_terbesar']
    report_lines.append(f"\n🔥 GEMPA TERBESAR (M={format_float(g_max['magnitudo'])}):")
    report_lines.append(f"   • Waktu: {g_max['waktu']}")
    report_lines.append(f"   • Lokasi: ({format_float(g_max['koordinat'][0])}, "
                       f"{format_float(g_max['koordinat'][1])}, "
                       f"{format_float(g_max['koordinat'][2])}) m")
    report_lines.append(f"   • Jarak dari pusat: {format_float(g_max['jarak'])} m")

    # Kedalaman
    report_lines.append(f"\n🌊 ANALISIS KEDALAMAN:")
    depth = results['kedalaman']
    report_lines.append(f"   • Rata-rata: {format_float(depth['mean'])} m")
    report_lines.append(f"   • Distribusi: {results['distribusi_kedalaman']['dangkal']} dangkal, "
                       f"{results['distribusi_kedalaman']['dalam']} dalam")

    # Zona
    report_lines.append(f"\n📍 ANALISIS ZONA:")
    zone = results['distribusi_zona']
    report_lines.append(f"   • Zona Dekat (<{config.RADIUS_THRESHOLD} m): {zone['dekat']} kejadian")
    report_lines.append(f"   • Zona Jauh (≥{config.RADIUS_THRESHOLD} m): {zone['jauh']} kejadian")

    if 'zona_dekat_stats' in results:
        stats = results['zona_dekat_stats']
        report_lines.append(f"   • Magnitudo rata-rata zona dekat: {format_float(stats['mean_magnitudo'])}")

    # 3. Rekomendasi
    report_lines.append("\n" + "-" * 70)
    report_lines.append("REKOMENDASI")
    report_lines.append("-" * 70)

    recommendations = [
        "1. Lakukan kalibrasi alat monitoring secara berkala",
        "2. Tingkatkan frekuensi monitoring jika aktivitas meningkat",
        "3. Dokumentasikan semua kejadian untuk analisis tren jangka panjang",
        "4. Lakukan investigasi lapangan untuk kejadian dengan magnitudo > 3.0",
        "5. Evaluasi protokol keselamatan berdasarkan zona aktivitas"
    ]

    report_lines.extend(recommendations)

    # 4. Metadata
    report_lines.append("\n" + "-" * 70)
    report_lines.append("METADATA ANALISIS")
    report_lines.append("-" * 70)
    report_lines.append(f"Parameter Analisis:")
    report_lines.append(f"  • Batas magnitudo valid: > {config.MIN_MAGNITUDO}")
    report_lines.append(f"  • Batas kedalaman dangkal: > {config.DEPTH_THRESHOLD} m")
    report_lines.append(f"  • Radius zona dekat: < {config.RADIUS_THRESHOLD} m")
    report_lines.append(f"  • Pusat monitoring: {config.MONITORING_CENTER}")

    # Tulis ke file
    with open(config.OUTPUT_REPORT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report_lines))

    print(f"✅ Laporan disimpan sebagai '{config.OUTPUT_REPORT}'")

    # Tampilkan preview laporan
    print("\n📄 Preview Laporan (10 baris pertama):")
    print("-" * 50)
    with open(config.OUTPUT_REPORT, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i < 10:
                print(line.rstrip())
            else:
                break

# 5. FUNGSI UTAMA
def main():
    """Fungsi utama untuk menjalankan seluruh alur analisis"""
    print_section_header("ANALISIS DATA MIKROSEISMIK", width=80)
    print("Memulai analisis...\n")

    try:
        # Langkah 1: Muat dan inspeksi data
        df_raw = load_and_inspect_data(config.INPUT_FILE)

        # Langkah 2: Bersihkan data
        df_clean = clean_data(df_raw)

        # Langkah 3: Preprocessing
        df_processed = preprocess_data(df_clean)

        # Langkah 4: Analisis
        results = analyze_data(df_processed)

        # Langkah 5: Visualisasi
        visualize_data(df_processed, results)

        # Langkah 6: Buat laporan
        generate_report(results, df_processed)

        # Langkah 7: Simpan data terproses
        df_processed.to_csv(config.OUTPUT_PROCESSED, index=False)
        print(f"\n✅ Data terproses disimpan sebagai '{config.OUTPUT_PROCESSED}'")

        # Ringkasan eksekusi
        print_section_header("RINGKASAN EKSEKUSI", width=80)
        print(f"📁 File yang dihasilkan:")
        print(f"   • {config.OUTPUT_REPORT} - Laporan analisis")
        print(f"   • {config.OUTPUT_PROCESSED} - Data terproses")
        print(f"   • {config.OUTPUT_VISUALIZATION} - Visualisasi")

        print(f"\n📊 Hasil Analisis:")
        print(f"   • Data valid: {results['total_data']:,} kejadian")
        print(f"   • Magnitudo rata-rata: {format_float(results['magnitudo']['mean'])}")
        print(f"   • Kedalaman rata-rata: {format_float(results['kedalaman']['mean'])} m")
        print(f"   • Kejadian zona dekat: {results['distribusi_zona']['dekat']:,}")

        print("\n" + "=" * 80)
        print("✅ ANALISIS SELESAI DENGAN SUKSES!".center(80))
        print("=" * 80)

    except Exception as e:
        print(f"\n❌ ERROR: Terjadi kesalahan selama analisis")
        print(f"   Pesan error: {str(e)}")
        raise

# 6. EKSEKUSI
if __name__ == "__main__":
    main()