# -*- coding: utf-8 -*-
"""123120079_Bintang Putra Permana_Modul 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TkErCaTozDL8KOFe2-viw4O6OJwP9VMb
"""

import random
from tabulate import tabulate

# KELAS DASAR DAN TURUNAN

class Sensor:
    """Kelas dasar untuk semua sensor geofisika"""

    def __init__(self, id_sensor, lokasi):
        self.id_sensor = id_sensor
        self.lokasi = lokasi
        self.status = "nonaktif"  # Default status
        self.data = []  # List untuk menyimpan data hasil rekaman

    def aktifkan_sensor(self):
        """Mengaktifkan sensor"""
        self.status = "aktif"
        print(f"Sensor {self.id_sensor} di {self.lokasi} telah diaktifkan.")

    def nonaktifkan_sensor(self):
        """Menonaktifkan sensor"""
        self.status = "nonaktif"
        print(f"Sensor {self.id_sensor} di {self.lokasi} telah dinonaktifkan.")

    def rekam_data(self):
        """Metode abstrak untuk merekam data (akan dioverride oleh kelas turunan)"""
        pass

    def jumlah_data(self):
        """Mengembalikan jumlah data yang telah direkam"""
        return len(self.data)

    def rata_rata_data(self):
        """Menghitung rata-rata data yang telah direkam"""
        if self.data:
            return sum(self.data) / len(self.data)
        return 0.0

    def info_sensor(self):
        """Mengembalikan informasi dasar sensor"""
        return {
            "ID": self.id_sensor,
            "Lokasi": self.lokasi,
            "Status": self.status,
            "Jenis": self.__class__.__name__,
            "Jumlah Data": self.jumlah_data(),
            "Rata-rata": round(self.rata_rata_data(), 4)
        }


class SensorSeismik(Sensor):
    """Kelas turunan untuk sensor seismik"""

    def __init__(self, id_sensor, lokasi, frekuensi_sampling, sensitivitas):
        super().__init__(id_sensor, lokasi)
        self.frekuensi_sampling = frekuensi_sampling  # dalam Hz
        self.sensitivitas = sensitivitas  # dalam V/m/s
        self.jenis = "Seismik"

    def rekam_data(self):
        """Merekam data seismik acak"""
        if self.status == "aktif":
            # Simulasi data amplitudo seismik (dalam mikrometer)
            amplitudo = random.uniform(0.1, 10.0)
            self.data.append(amplitudo)
            return amplitudo
        else:
            print(f"Peringatan: Sensor {self.id_sensor} tidak aktif!")
            return None

    def info_sensor(self):
        """Override info_sensor dengan informasi tambahan"""
        info = super().info_sensor()
        info["Frekuensi Sampling"] = f"{self.frekuensi_sampling} Hz"
        info["Sensitivitas"] = f"{self.sensitivitas} V/m/s"
        return info


class SensorGravitasi(Sensor):
    """Kelas turunan untuk sensor gravitasi"""

    def __init__(self, id_sensor, lokasi, akurasi, rentang_pengukuran):
        super().__init__(id_sensor, lokasi)
        self.akurasi = akurasi  # dalam mGal
        self.rentang_pengukuran = rentang_pengukuran  # dalam Gal
        self.jenis = "Gravitasi"

    def rekam_data(self):
        """Merekam data gravitasi acak"""
        if self.status == "aktif":
            # Simulasi data percepatan gravitasi (dalam m/s^2)
            # Nilai normal sekitar 9.78-9.83 m/s^2 di permukaan bumi
            gravitasi = random.uniform(9.78, 9.83)
            self.data.append(gravitasi)
            return gravitasi
        else:
            print(f"Peringatan: Sensor {self.id_sensor} tidak aktif!")
            return None

    def info_sensor(self):
        """Override info_sensor dengan informasi tambahan"""
        info = super().info_sensor()
        info["Akurasi"] = f"{self.akurasi} mGal"
        info["Rentang"] = f"{self.rentang_pengukuran} Gal"
        return info


# FUNGSI UTILITAS

def buat_laporan(sensor_list):
    """Membuat laporan tabel dari semua sensor"""
    if not sensor_list:
        print("Tidak ada sensor yang terdaftar.")
        return

    # Mengumpulkan informasi dari semua sensor
    data_laporan = []
    for sensor in sensor_list:
        info = sensor.info_sensor()
        data_laporan.append([
            info["ID"],
            info["Lokasi"],
            info["Jenis"],
            info["Status"],
            info["Jumlah Data"],
            info["Rata-rata"]
        ])

    # Menampilkan tabel
    headers = ["ID Sensor", "Lokasi", "Jenis", "Status", "Jumlah Data", "Rata-rata"]
    print("\n" + "="*80)
    print("LAPORAN SISTEM SENSOR GEOFISIKA")
    print("="*80)
    print(tabulate(data_laporan, headers=headers, tablefmt="grid", numalign="center"))
    print("="*80)


def simulasi_pencatatan(sensor_list, jumlah_pembacaan=10):
    """Melakukan simulasi pencatatan data dari semua sensor aktif"""
    print(f"\nMemulai simulasi pencatatan data ({jumlah_pembacaan} pembacaan)...")

    for i in range(jumlah_pembacaan):
        print(f"\n--- Pembacaan ke-{i+1} ---")
        for sensor in sensor_list:
            if sensor.status == "aktif":
                data = sensor.rekam_data()
                if data:
                    print(f"  {sensor.id_sensor} ({sensor.lokasi}): {data:.4f}")


# PROGRAM UTAMA

def main():
    """Fungsi utama program"""
    print("="*80)
    print("SISTEM MANAJEMEN SENSOR GEOFISIKA")
    print("="*80)

    # Membuat daftar sensor
    sensor_list = []

    # Membuat objek sensor seismik
    seismik1 = SensorSeismik("SS001", "Gunung Merapi", 100, 1500)
    seismik2 = SensorSeismik("SS002", "Laut Jawa", 200, 2000)

    # Membuat objek sensor gravitasi
    gravitasi1 = SensorGravitasi("SG001", "Bandung", 0.01, 10)
    gravitasi2 = SensorGravitasi("SG002", "Papua", 0.005, 15)

    # Menambahkan sensor ke dalam list
    sensor_list.extend([seismik1, seismik2, gravitasi1, gravitasi2])

    # Mengaktifkan sensor
    print("\nMengaktifkan sensor...")
    seismik1.aktifkan_sensor()
    gravitasi1.aktifkan_sensor()
    gravitasi2.aktifkan_sensor()

    # Melakukan beberapa rekaman data awal
    print("\nMelakukan rekaman data awal...")
    for _ in range(5):
        seismik1.rekam_data()
        gravitasi1.rekam_data()
        gravitasi2.rekam_data()

    # Menampilkan laporan awal
    buat_laporan(sensor_list)

    # Melakukan simulasi pencatatan otomatis
    simulasi_pencatatan(sensor_list, 8)

    # Mengaktifkan sensor yang masih nonaktif
    print("\nMengaktifkan sensor yang masih nonaktif...")
    seismik2.aktifkan_sensor()

    # Melakukan simulasi pencatatan lagi
    simulasi_pencatatan(sensor_list, 5)

    # Menonaktifkan salah satu sensor
    print("\nMenonaktifkan salah satu sensor...")
    gravitasi1.nonaktifkan_sensor()

    # Melakukan simulasi pencatatan terakhir
    simulasi_pencatatan(sensor_list, 3)

    # Menampilkan laporan akhir
    print("\n" + "="*80)
    print("LAPORAN AKHIR")
    print("="*80)
    buat_laporan(sensor_list)

    # Menampilkan detail setiap sensor
    print("\nDETAIL SETIAP SENSOR:")
    print("-"*80)
    for sensor in sensor_list:
        info = sensor.info_sensor()
        print(f"\nSensor {info['ID']} - {info['Jenis']}:")
        print(f"  Lokasi: {info['Lokasi']}")
        print(f"  Status: {info['Status']}")
        print(f"  Jumlah data: {info['Jumlah Data']}")
        print(f"  Rata-rata: {info['Rata-rata']}")

        # Menampilkan informasi tambahan berdasarkan jenis sensor
        if hasattr(sensor, 'frekuensi_sampling'):
            print(f"  Frekuensi sampling: {sensor.frekuensi_sampling} Hz")
            print(f"  Sensitivitas: {sensor.sensitivitas} V/m/s")
        if hasattr(sensor, 'akurasi'):
            print(f"  Akurasi: {sensor.akurasi} mGal")
            print(f"  Rentang pengukuran: {sensor.rentang_pengukuran} Gal")

        # Menampilkan 5 data terakhir jika ada
        if sensor.data:
            print(f"  5 data terakhir: {[round(x, 4) for x in sensor.data[-5:]]}")

    print("\n" + "="*80)
    print("Program selesai. Terima kasih!")
    print("="*80)


# EKSEKUSI PROGRAM


if __name__ == "__main__":
    main()