# -*- coding: utf-8 -*-
"""123120079_Bintang Putra Permana_Challenge 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEEd_Xp7QK-2XOdSdHeCWksn98LmLJfb
"""

import streamlit as st
import segyio
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import io
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Konfigurasi halaman Streamlit
st.set_page_config(
    page_title="Visualisasi Data Seismik SEG-Y",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Judul aplikasi
st.title("📊 Visualisasi Data Seismik SEG-Y")
st.markdown("""
Aplikasi ini memungkinkan visualisasi interaktif data seismik Post-Stack dalam format SEG-Y.
Gunakan kontrol di sidebar untuk menyesuaikan tampilan data.
""")

# Fungsi untuk membaca data SEG-Y
def load_segy_data(segy_path):
    """Membaca data SEG-Y dan header-nya"""
    try:
        with segyio.open(segy_path, "r", ignore_geometry=True) as f:
            # Informasi dasar dari binary header
            ns = f.bin[segyio.BinField.Samples]
            ntraces = f.tracecount
            dt = f.bin[segyio.BinField.Interval]

            # Baca data seismik
            data = np.zeros((ntraces, ns), dtype=np.float32)
            for i in range(ntraces):
                data[i, :] = f.trace[i]

            # Baca header teks
            text_header = segyio.tools.wrap(f.text[0]) if hasattr(f, 'text') and len(f.text) > 0 else ""

            # Baca trace header untuk beberapa field penting
            trace_headers = {}
            trace_fields = {
                "CDP": segyio.TraceField.CDP,
                "CDP_X": segyio.TraceField.CDP_X,
                "CDP_Y": segyio.TraceField.CDP_Y,
                "INLINE_3D": segyio.TraceField.INLINE_3D,
                "CROSSLINE_3D": segyio.TraceField.CROSSLINE_3D,
                "SourceX": segyio.TraceField.SourceX,
                "SourceY": segyio.TraceField.SourceY,
                "GroupX": segyio.TraceField.GroupX,
                "GroupY": segyio.TraceField.GroupY,
                "Offset": segyio.TraceField.Offset,
                "TRACE_SAMPLE_COUNT": segyio.TraceField.TRACE_SAMPLE_COUNT,
            }

            # Kumpulkan data header
            for field_name, field_code in trace_fields.items():
                values = []
                for i in range(ntraces):
                    try:
                        value = f.header[i][field_code]
                        values.append(value)
                    except:
                        values.append(np.nan)
                trace_headers[field_name] = values

            # Buat DataFrame dari trace headers
            df_trace_headers = pd.DataFrame(trace_headers)

            # Informasi tambahan
            info = {
                "ns": ns,
                "ntraces": ntraces,
                "dt": dt,
                "data_format": f.bin[segyio.BinField.Format],
                "text_header": text_header,
                "binary_header": dict(f.bin)
            }

            return data, df_trace_headers, info

    except Exception as e:
        st.error(f"Error membaca file SEG-Y: {str(e)}")
        return None, None, None

# Fungsi untuk membuat colormap kustom
def create_custom_colormaps():
    """Membuat beberapa colormap kustom untuk data seismik"""
    # Seismic colormap (biru-putih-merah)
    seismic_cmap = LinearSegmentedColormap.from_list(
        'seismic_custom',
        ['#0000FF', '#FFFFFF', '#FF0000'],
        N=256
    )

    # Grayscale colormap
    grayscale_cmap = LinearSegmentedColormap.from_list(
        'grayscale_custom',
        ['#000000', '#FFFFFF'],
        N=256
    )

    # Rainbow colormap
    rainbow_cmap = LinearSegmentedColormap.from_list(
        'rainbow_custom',
        ['#FF0000', '#FFFF00', '#00FF00', '#00FFFF', '#0000FF', '#FF00FF'],
        N=256
    )

    return {
        "viridis": plt.cm.viridis,
        "plasma": plt.cm.plasma,
        "seismic": seismic_cmap,
        "gray": grayscale_cmap,
        "rainbow": rainbow_cmap,
        "jet": plt.cm.jet,
        "hot": plt.cm.hot,
        "cool": plt.cm.cool,
        "bone": plt.cm.bone
    }

# Inisialisasi session state untuk menyimpan data
if 'data' not in st.session_state:
    st.session_state.data = None
if 'df_headers' not in st.session_state:
    st.session_state.df_headers = None
if 'info' not in st.session_state:
    st.session_state.info = None

# Sidebar untuk upload file dan kontrol
with st.sidebar:
    st.header("📁 Upload Data")

    # Upload file SEG-Y
    uploaded_file = st.file_uploader("Pilih file SEG-Y", type=['sgy', 'segy'])

    # Atau gunakan file contoh (opsional)
    use_example = st.checkbox("Gunakan data contoh (jika tidak ada file)")

    if uploaded_file is not None:
        # Simpan file yang diupload ke temporary file
        with open("temp_segy.sgy", "wb") as f:
            f.write(uploaded_file.getbuffer())

        # Baca data
        if st.button("Load Data") or st.session_state.data is None:
            with st.spinner("Membaca data SEG-Y..."):
                data, df_headers, info = load_segy_data("temp_segy.sgy")

                if data is not None:
                    st.session_state.data = data
                    st.session_state.df_headers = df_headers
                    st.session_state.info = info
                    st.success("Data berhasil dimuat!")

    elif use_example:
        st.info("Fitur data contoh belum diimplementasikan. Silakan upload file SEG-Y Anda.")

    # Tampilkan informasi data jika sudah dimuat
    if st.session_state.data is not None:
        st.header("ℹ️ Informasi Data")
        st.write(f"Jumlah Trace: {st.session_state.data.shape[0]}")
        st.write(f"Jumlah Sample per Trace: {st.session_state.data.shape[1]}")
        st.write(f"Interval Sample (µs): {st.session_state.info['dt']}")

        st.header("🎛️ Kontrol Visualisasi")

        # Pilihan colormap
        colormaps = create_custom_colormaps()
        cmap_names = list(colormaps.keys())
        selected_cmap = st.selectbox(
            "Pilih Colormap",
            cmap_names,
            index=cmap_names.index("seismic") if "seismic" in cmap_names else 0
        )

        # Mode scaling
        scale_mode = st.radio(
            "Mode Scaling",
            ["Auto", "Manual"],
            index=0
        )

        # Slider untuk vmin dan vmax jika mode manual
        if scale_mode == "Manual":
            if st.session_state.data is not None:
                data_min = np.nanmin(st.session_state.data)
                data_max = np.nanmax(st.session_state.data)

                col1, col2 = st.columns(2)
                with col1:
                    vmin = st.slider(
                        "Min Value (vmin)",
                        float(data_min),
                        float(data_max),
                        float(data_min),
                        step=float((data_max - data_min) / 100)
                    )
                with col2:
                    vmax = st.slider(
                        "Max Value (vmax)",
                        float(data_min),
                        float(data_max),
                        float(data_max),
                        step=float((data_max - data_min) / 100)
                    )
        else:
            vmin = None
            vmax = None

        # Opsi tambahan
        st.header("⚙️ Opsi Tambahan")

        # Opsi membalik sumbu waktu
        reverse_time = st.checkbox("Balik Sumbu Waktu", value=False)

        # Opsi memilih rentang trace
        show_trace_range = st.checkbox("Pilih Rentang Trace", value=False)

        if show_trace_range and st.session_state.data is not None:
            ntraces = st.session_state.data.shape[0]
            trace_range = st.slider(
                "Rentang Trace",
                0, ntraces-1, (0, min(100, ntraces-1))
            )
        else:
            trace_range = None

        # Opsi gain
        apply_gain = st.checkbox("Terapkan Gain", value=False)
        if apply_gain:
            gain_value = st.slider("Nilai Gain", 0.1, 5.0, 1.0, 0.1)
        else:
            gain_value = 1.0

# Area utama aplikasi
if st.session_state.data is not None:
    # Tampilkan informasi data
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Jumlah Trace", st.session_state.data.shape[0])
    with col2:
        st.metric("Samples per Trace", st.session_state.data.shape[1])
    with col3:
        st.metric("Interval Sample (µs)", st.session_state.info['dt'])

    # Tab untuk berbagai visualisasi
    tab1, tab2, tab3, tab4 = st.tabs(["Plot Seismik", "Data Header", "Statistik", "Ekspor"])

    with tab1:
        # Siapkan data untuk plotting
        data_to_plot = st.session_state.data.copy()

        # Terapkan gain jika dipilih
        if apply_gain:
            data_to_plot = data_to_plot * gain_value

        # Potong data sesuai rentang trace jika dipilih
        if trace_range is not None:
            data_to_plot = data_to_plot[trace_range[0]:trace_range[1], :]

        # Balik sumbu waktu jika dipilih
        if reverse_time:
            data_to_plot = np.flipud(data_to_plot.T).T

        # Plot dengan matplotlib
        st.subheader("Plot Data Seismik")

        fig, ax = plt.subplots(figsize=(12, 8))

        # Tentukan vmin dan vmax
        if scale_mode == "Manual":
            im = ax.imshow(data_to_plot.T,
                          aspect='auto',
                          cmap=colormaps[selected_cmap],
                          vmin=vmin,
                          vmax=vmax)
        else:
            im = ax.imshow(data_to_plot.T,
                          aspect='auto',
                          cmap=colormaps[selected_cmap])

        ax.set_xlabel('Trace Number', fontsize=12)
        ax.set_ylabel('Sample Number', fontsize=12)
        ax.set_title(f'Seismic Section (Colormap: {selected_cmap})', fontsize=14)

        # Tambahkan colorbar
        cbar = plt.colorbar(im, ax=ax, orientation='vertical', pad=0.01)
        cbar.set_label('Amplitude', fontsize=12)

        st.pyplot(fig)

        # Juga tampilkan dengan plotly untuk interaktivitas lebih
        st.subheader("Plot Interaktif (Plotly)")

        # Buat plot dengan plotly
        fig_plotly = go.Figure(data=go.Heatmap(
            z=data_to_plot.T,
            colorscale=selected_cmap,
            zmin=vmin if scale_mode == "Manual" else None,
            zmax=vmax if scale_mode == "Manual" else None,
            colorbar=dict(title="Amplitude")
        ))

        fig_plotly.update_layout(
            title=f'Seismic Section - Interactive (Colormap: {selected_cmap})',
            xaxis_title='Trace Number',
            yaxis_title='Sample Number',
            height=600,
            width=1000
        )

        st.plotly_chart(fig_plotly, use_container_width=True)

        # Tampilkan trace individual jika dipilih
        st.subheader("Trace Individual")

        if trace_range is not None:
            max_trace = trace_range[1] - trace_range[0]
        else:
            max_trace = st.session_state.data.shape[0] - 1

        selected_trace = st.slider("Pilih Trace untuk Ditampilkan", 0, max_trace, 0)

        # Sesuaikan trace number jika menggunakan rentang
        if trace_range is not None:
            actual_trace = trace_range[0] + selected_trace
        else:
            actual_trace = selected_trace

        fig2, ax2 = plt.subplots(figsize=(10, 6))
        ax2.plot(data_to_plot[selected_trace, :], 'b-', linewidth=1.5)
        ax2.axhline(y=0, color='k', linestyle='-', linewidth=0.5)
        ax2.set_xlabel('Sample Number', fontsize=12)
        ax2.set_ylabel('Amplitude', fontsize=12)
        ax2.set_title(f'Trace {actual_trace}', fontsize=14)
        ax2.grid(True, alpha=0.3)

        st.pyplot(fig2)

    with tab2:
        st.subheader("Data Trace Header")

        # Tampilkan DataFrame dengan trace headers
        st.dataframe(st.session_state.df_headers, height=400)

        # Pilih kolom untuk visualisasi
        st.subheader("Visualisasi Header")

        selected_header = st.selectbox(
            "Pilih Header untuk Plot",
            st.session_state.df_headers.columns.tolist()
        )

        if selected_header:
            fig3, ax3 = plt.subplots(figsize=(10, 4))
            ax3.plot(st.session_state.df_headers[selected_header].values, 'b-', linewidth=1.5)
            ax3.set_xlabel('Trace Number', fontsize=12)
            ax3.set_ylabel(selected_header, fontsize=12)
            ax3.set_title(f'Trace Header: {selected_header}', fontsize=14)
            ax3.grid(True, alpha=0.3)

            st.pyplot(fig3)

    with tab3:
        st.subheader("Statistik Data")

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**Statistik Deskriptif Amplitude**")
            # Hitung statistik
            stats_data = {
                "Min": np.nanmin(st.session_state.data),
                "Max": np.nanmax(st.session_state.data),
                "Mean": np.nanmean(st.session_state.data),
                "Std Dev": np.nanstd(st.session_state.data),
                "Median": np.nanmedian(st.session_state.data)
            }

            # Tampilkan sebagai DataFrame
            stats_df = pd.DataFrame(list(stats_data.items()), columns=['Statistic', 'Value'])
            st.dataframe(stats_df, use_container_width=True)

        with col2:
            st.markdown("**Histogram Amplitude**")

            # Flatten data untuk histogram
            flattened_data = st.session_state.data.flatten()
            # Hapus NaN jika ada
            flattened_data = flattened_data[~np.isnan(flattened_data)]

            fig4, ax4 = plt.subplots(figsize=(8, 6))
            ax4.hist(flattened_data, bins=100, color='skyblue', edgecolor='black', alpha=0.7)
            ax4.set_xlabel('Amplitude', fontsize=12)
            ax4.set_ylabel('Frequency', fontsize=12)
            ax4.set_title('Distribution of Seismic Amplitudes', fontsize=14)
            ax4.grid(True, alpha=0.3)

            st.pyplot(fig4)

    with tab4:
        st.subheader("Ekspor Plot dan Data")

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**Ekspor Plot sebagai Gambar**")

            # Buat plot untuk diekspor
            export_fig, export_ax = plt.subplots(figsize=(10, 6))
            im_export = export_ax.imshow(st.session_state.data.T, aspect='auto', cmap=colormaps[selected_cmap])
            export_ax.set_xlabel('Trace Number', fontsize=12)
            export_ax.set_ylabel('Sample Number', fontsize=12)
            export_ax.set_title(f'Seismic Section - {datetime.now().strftime("%Y-%m-%d")}', fontsize=14)
            plt.colorbar(im_export, ax=export_ax).set_label('Amplitude', fontsize=12)

            # Konversi plot ke format PNG
            buf = io.BytesIO()
            export_fig.savefig(buf, format='png', dpi=150, bbox_inches='tight')
            buf.seek(0)

            st.download_button(
                label="Unduh Plot sebagai PNG",
                data=buf,
                file_name=f"seismic_plot_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png",
                mime="image/png"
            )

        with col2:
            st.markdown("**Ekspor Statistik sebagai CSV**")

            # Siapkan data statistik untuk diekspor
            export_stats = pd.DataFrame({
                'Parameter': ['Min Amplitude', 'Max Amplitude', 'Mean Amplitude',
                             'Std Dev Amplitude', 'Median Amplitude', 'Number of Traces',
                             'Samples per Trace', 'Sample Interval (µs)'],
                'Value': [np.nanmin(st.session_state.data),
                         np.nanmax(st.session_state.data),
                         np.nanmean(st.session_state.data),
                         np.nanstd(st.session_state.data),
                         np.nanmedian(st.session_state.data),
                         st.session_state.data.shape[0],
                         st.session_state.data.shape[1],
                         st.session_state.info['dt']]
            })

            # Konversi ke CSV
            csv_stats = export_stats.to_csv(index=False)

            st.download_button(
                label="Unduh Statistik sebagai CSV",
                data=csv_stats,
                file_name=f"seismic_stats_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                mime="text/csv"
            )

else:
    # Tampilkan instruksi jika belum ada data
    st.info("""
    👈 **Silakan upload file SEG-Y Anda di sidebar**

    Atau gunakan checkbox "Gunakan data contoh" jika Anda ingin mencoba dengan data contoh.

    Setelah data dimuat, Anda dapat:
    1. Memilih colormap yang berbeda untuk visualisasi
    2. Mengatur skala amplitudo (Auto atau Manual dengan slider vmin/vmax)
    3. Membalik sumbu waktu jika diperlukan
    4. Memilih rentang trace tertentu untuk ditampilkan
    5. Menyimpan plot sebagai gambar PNG
    """)

    # Tambahkan contoh gambar untuk demonstrasi
    st.subheader("Contoh Output Visualisasi Data Seismik")

    # Buat data sintetik untuk demonstrasi
    example_data = np.random.randn(100, 200) * np.exp(-np.linspace(0, 3, 200))
    example_data = example_data + np.sin(np.linspace(0, 10, 100))[:, np.newaxis]

    fig_example, ax_example = plt.subplots(figsize=(10, 6))
    im_example = ax_example.imshow(example_data.T, aspect='auto', cmap='seismic')
    ax_example.set_xlabel('Trace Number', fontsize=12)
    ax_example.set_ylabel('Sample Number', fontsize=12)
    ax_example.set_title('Contoh Plot Data Seismik', fontsize=14)
    plt.colorbar(im_example, ax=ax_example).set_label('Amplitude', fontsize=12)

    st.pyplot(fig_example)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center'>
        <p>Aplikasi Visualisasi Data Seismik SEG-Y | Dibuat dengan Streamlit, segyio, dan Matplotlib</p>
        <p>Challenge: Implementasi Library Streamlit untuk Visualisasi dan Pemrosesan Data Seismik</p>
    </div>
    """,
    unsafe_allow_html=True
)